app = "aiphoto-backend"
primary_region = "sin"

[build]

[deploy]
  release_command = "npm install"

[run]
  port = 8080
  protocol = "tcp"
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"