services:
  - type: web
    name: aiphoto-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /
    autoDeploy: true
    disk: null
    regions:
      - singapore